// This file was auto-generated by ML.NET Model Builder. 

using System;
using HeartDiseaseСlassificationML.Model;

namespace HeartDiseaseСlassificationML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Age = 63F,
                Sex = 1F,
                Trestbps = 145F,
                Chol = 233F,
                Fbs = 1F,
                Restecg = 0F,
                Thalach = 150F,
                Exang = 0F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Cp with predicted Cp from sample data...\n\n");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Sex: {sampleData.Sex}");
            Console.WriteLine($"Trestbps: {sampleData.Trestbps}");
            Console.WriteLine($"Chol: {sampleData.Chol}");
            Console.WriteLine($"Fbs: {sampleData.Fbs}");
            Console.WriteLine($"Restecg: {sampleData.Restecg}");
            Console.WriteLine($"Thalach: {sampleData.Thalach}");
            Console.WriteLine($"Exang: {sampleData.Exang}");
            Console.WriteLine($"\n\nPredicted Cp value {predictionResult.Prediction} \nPredicted Cp scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
