// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HeartDiseaseСlassificationML.Model
{
    public class ModelInput
    {
        [ColumnName("age"), LoadColumn(0)]
        public float Age { get; set; }


        [ColumnName("sex"), LoadColumn(1)]
        public float Sex { get; set; }


        [ColumnName("trestbps"), LoadColumn(2)]
        public float Trestbps { get; set; }


        [ColumnName("chol"), LoadColumn(3)]
        public float Chol { get; set; }


        [ColumnName("fbs"), LoadColumn(4)]
        public float Fbs { get; set; }


        [ColumnName("restecg"), LoadColumn(5)]
        public float Restecg { get; set; }


        [ColumnName("thalach"), LoadColumn(6)]
        public float Thalach { get; set; }


        [ColumnName("exang"), LoadColumn(7)]
        public float Exang { get; set; }


        [ColumnName("cp"), LoadColumn(8)]
        public string Cp { get; set; }


    }
}
