// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;
using System.ComponentModel.DataAnnotations;

namespace HeartDiseaseСlassificationML.Model
{
    public class ModelInput
    {
        [Required]
        [Range(1, 150, ErrorMessage = "Wrong range.")]
        [ColumnName("age"), LoadColumn(0)]
        public float Age { get; set; }

        [Required]
        [Range(0, 1, ErrorMessage = "Wrong range.")]
        [ColumnName("sex"), LoadColumn(1)]
        public float Sex { get; set; }

        [Required]
        [Range(90, 210, ErrorMessage = "Wrong range.")]
        [ColumnName("trestbps"), LoadColumn(2)]
        public float Trestbps { get; set; }

        [Required]
        [Range(100, 600, ErrorMessage = "Wrong range.")]
        [ColumnName("chol"), LoadColumn(3)]
        public float Chol { get; set; }

        [Required]
        [Range(0, 1, ErrorMessage = "Wrong range.")]
        [ColumnName("fbs"), LoadColumn(4)]
        public float Fbs { get; set; }

        [Required]
        [Range(0, 2, ErrorMessage = "Wrong range.")]
        [ColumnName("restecg"), LoadColumn(5)]
        public float Restecg { get; set; }

        [Required]
        [Range(60, 210, ErrorMessage = "Wrong range.")]
        [ColumnName("thalach"), LoadColumn(6)]
        public float Thalach { get; set; }

        [Required]
        [Range(0, 1, ErrorMessage = "Wrong range.")]
        [ColumnName("exang"), LoadColumn(7)]
        public float Exang { get; set; }


        [ColumnName("cp"), LoadColumn(8)]
        public string Cp { get; set; }


    }
}
